language: c

matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.02 MODE=opam
    - os: linux
      env: OCAML_VERSION=4.03 MODE=opam
    - os: linux
      env: OCAML_VERSION=4.04 MODE=opam
    - os: linux
      env: OCAML_VERSION=4.05 MODE=opam
    - os: linux
      env: OCAML_VERSION=4.06 MODE=opam
    - os: linux
      env: OCAML_VERSION=4.07 MODE=opam
    - os: linux
      env: OCAML_VERSION=4.07 MODE=build
      name: "4.07 all targets"
    - os: osx
      env: OCAML_VERSION=system

  allow_failures:
    - os: linux
      env: OCAML_VERSION=4.02 MODE=opam
    - os: linux
      env: OCAML_VERSION=4.03 MODE=opam
    - os: osx
      env: OCAML_VERSION=system MODE=opam

  fast_finish: true

script: bash -e tools/travis.sh

# safelist
branches:
  only:
  - master
  - wikidoc